import type { Reservation, Customer, QuestionnaireData } from '@/types'
import { CONFIRMED_STATUS_ID, DEFAULT_STATUS_ID } from './masters'

// ─── 予約データ ────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10)
const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10)
const now = new Date().toISOString()

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: `R-${today.replace(/-/g, '')}-001`,
    createdAt: now,
    updatedAt: now,
    customerId: 'C002',
    guestName: '田中 花子',
    guestPhone: '090-1234-5678',
    guestEmail: 'tanaka@example.com',
    diveDate: today,
    timeSlot: 'morning',
    courseId: 'CRS-001',
    courseName: '体験ダイビング',
    guestCount: 2,
    status: CONFIRMED_STATUS_ID,
    staffId: 'STF-001',
    staffName: '外間 健',
    channel: 'hp',
    questionnaireCompleted: true,
    staffNote: 'カップル。写真希望あり',
  },
  {
    id: `R-${today.replace(/-/g, '')}-002`,
    createdAt: now,
    updatedAt: now,
    customerId: 'C001',
    guestName: '鈴木 太郎',
    guestPhone: '080-9876-5432',
    guestEmail: '',
    diveDate: today,
    timeSlot: 'afternoon',
    courseId: 'CRS-002',
    courseName: 'ファンダイビング（2本）',
    guestCount: 1,
    status: CONFIRMED_STATUS_ID,
    staffId: 'STF-001',
    staffName: '外間 健',
    channel: 'phone',
    questionnaireCompleted: false,
    staffNote: 'AOW 総本数150本',
  },
  {
    id: `R-${today.replace(/-/g, '')}-003`,
    createdAt: now,
    updatedAt: now,
    guestName: '山田 家族',
    guestPhone: '070-1111-2222',
    guestEmail: '',
    diveDate: today,
    timeSlot: 'morning',
    courseId: 'CRS-001',
    courseName: '体験ダイビング',
    guestCount: 3,
    status: DEFAULT_STATUS_ID,
    channel: 'ota',
    questionnaireCompleted: false,
  },
  {
    id: `R-${tomorrow.replace(/-/g, '')}-001`,
    createdAt: now,
    updatedAt: now,
    customerId: 'C001',
    guestName: '佐藤 一郎',
    guestPhone: '090-3333-4444',
    guestEmail: '',
    diveDate: tomorrow,
    timeSlot: 'morning',
    courseId: 'CRS-004',
    courseName: 'ナイトダイビング',
    guestCount: 2,
    status: CONFIRMED_STATUS_ID,
    staffId: 'STF-002',
    staffName: '知念 美咲',
    channel: 'email',
    questionnaireCompleted: true,
  },
]

const RES_ID = {
  R1: MOCK_RESERVATIONS[0].id,
  R4: MOCK_RESERVATIONS[3].id,
}

// ─── 問診票データ ───────────────────────────────────────────
export const MOCK_QUESTIONNAIRES: QuestionnaireData[] = [
  {
    id: 'Q001',
    reservationId: RES_ID.R1,
    submittedAt: new Date().toISOString(),
    lastName: '田中',
    firstName: '花子',
    lastNameKana: 'タナカ',
    firstNameKana: 'ハナコ',
    birthDate: '1995-06-15',
    gender: 'female',
    address: '東京都渋谷区',
    phone: '090-1234-5678',
    emergencyName: '田中 太郎',
    emergencyRelation: '夫',
    emergencyPhone: '090-0000-0001',
    heartDisease: false,
    respiratoryDisease: false,
    earDisease: false,
    epilepsy: false,
    diabetes: false,
    pregnant: false,
    panicDisorder: false,
    medication: false,
    medicationName: '',
    latexAllergy: false,
    sleepHours: 7,
    alcoholLastNight: false,
    alcoholToday: false,
    condition: 'good',
    flightWithin48h: false,
    hasCCard: false,
    cCardType: '',
    cCardOrg: '',
    lastDiveDate: '',
    totalDives: 0,
    agreeRisk: true,
    agreeMedical: true,
    agreePhoto: true,
  },
  {
    id: 'Q002',
    reservationId: RES_ID.R4,
    submittedAt: new Date(Date.now() - 3600000).toISOString(),
    lastName: '佐藤',
    firstName: '一郎',
    lastNameKana: 'サトウ',
    firstNameKana: 'イチロウ',
    birthDate: '1988-03-22',
    gender: 'male',
    address: '大阪府大阪市',
    phone: '090-3333-4444',
    emergencyName: '佐藤 美子',
    emergencyRelation: '妻',
    emergencyPhone: '080-5555-6666',
    heartDisease: false,
    respiratoryDisease: false,
    earDisease: true,
    epilepsy: false,
    diabetes: false,
    pregnant: false,
    panicDisorder: false,
    medication: false,
    medicationName: '',
    latexAllergy: false,
    sleepHours: 6,
    alcoholLastNight: false,
    alcoholToday: false,
    condition: 'good',
    flightWithin48h: false,
    hasCCard: true,
    cCardType: 'AOW',
    cCardOrg: 'PADI',
    lastDiveDate: '2026-03-10',
    totalDives: 150,
    agreeRisk: true,
    agreeMedical: true,
    agreePhoto: false,
  },
]

// ─── 顧客台帳データ ─────────────────────────────────────────
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'C001',
    lastName: '佐藤',
    firstName: '一郎',
    lastNameKana: 'サトウ',
    firstNameKana: 'イチロウ',
    phone: '090-3333-4444',
    email: 'sato@example.com',
    lastVisit: '2026-06-20',
    visitCount: 5,
    hasCCard: true,
    cCardType: 'AOW',
    totalDives: 150,
    healthNotes: '中耳炎の既往あり。耳抜き注意。',
    guideNotes: '慶良間諸島のアーチがお気に入り。水中写真好き。次回はケラマブルー狙いで早朝ダイブを提案。',
  },
  {
    id: 'C002',
    lastName: '田中',
    firstName: '花子',
    lastNameKana: 'タナカ',
    firstNameKana: 'ハナコ',
    phone: '090-1234-5678',
    email: 'tanaka@example.com',
    lastVisit: today,
    visitCount: 1,
    hasCCard: false,
    cCardType: '',
    totalDives: 0,
    healthNotes: '',
    guideNotes: '初ダイビング。カメに感動していた。Cカード取得を検討中とのこと。',
  },
  {
    id: 'C003',
    lastName: '山本',
    firstName: '健太',
    lastNameKana: 'ヤマモト',
    firstNameKana: 'ケンタ',
    phone: '080-7777-8888',
    email: '',
    lastVisit: '2026-05-05',
    visitCount: 12,
    hasCCard: true,
    cCardType: 'Rescue Diver',
    totalDives: 340,
    healthNotes: '特になし',
    guideNotes: '常連。深場好き。マンタシーズンには必ず来店。リクエストはいつも久米島。',
  },
]
